sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sledgersexpress/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sledgersexpress/docker-react npm run test
